## CHANGE this to the name of your plugin.
name: Endrex

## CHANGE this to your username.
author: nahkd123

## CHANGE this to a meaninful but short description of your plugin.
description: Add stuffs for the boring The End

## CHANGE this to the path of the class that extends JavaPlugin.
main: me.nahkd.spigot.sfaddons.endrex.Endrex

## You can change this to link to your website or repository. You can also remove this line if you want to.
website: https://github.com/nahkd123/Endrex

## This is required and marks Slimefun as a plugin dependency.
depend: [Slimefun]

## This value is automatically replaced by the version specified in your pom.xml file, do not change this.
version: ${project.version}

## This is the minimum minecraft version required to run your plugin.
api-version: "1.14"

api: []